BookStore/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using BookStore.Data;
using Newtonsoft.Json;

namespace BookStore.Controllers
{
    public class SearchController : Controller
    {
        BookStoreContext db = new BookStoreContext();

        // GET: Search
        public ActionResult Index(string key, int? costBegin, int? costEnd)
        {
            IQueryable<Product> products;
            if (!string.IsNullOrEmpty(key))
            {
                products = db.Products.Where(p => p.Name.Contains(key));
            }
            else
            {
                products = db.Products;
            }

            if (costBegin != null)
            {
                products = products.Where(p => p.CostPrice >= costBegin);
            }
            if (costEnd != null)
            {
                products = products.Where(p => p.CostPrice <= costEnd);
            }
            
            ViewData["Categories"] = db.Categories.ToList();
            ViewData["Authors"] = db.Authors.ToList();
            return View(products.ToList());
        }

        /// <summary>
        /// As same as the view above, but this only return json
        /// </summary>
        [HttpGet]
        public ActionResult Search(
            string key
            , int? authorId, int? categoryId
            , int? costBegin, int? costEnd)
        {
            if(costBegin!= null)
            {
                costBegin *= 1000;
            }
            if (costEnd != null)
            {
                costEnd *= 1000;
            }
            IQueryable<Product> products;
            if (!string.IsNullOrEmpty(key))
            {
                products = db.Products.Where(p => p.Name.Contains(key));
            }
            else
            {
                products = db.Products;
            }

            if (authorId != null)
            {
                List<Product> tmp = products.ToList();
                List<Product> tmp2 = new List<Product>(tmp);
                foreach(var singleProduct in tmp2)
                {
                    var details = singleProduct.ProductDetails;
                    if (details != null)
                    {
                        var found = details.Where(pd => pd.AuthorId == authorId);
                        if (found == null || found.Count() == 0)
                        {
                            tmp.Remove(singleProduct);
                        }
                    }
                }
                if (tmp.Count == 0)
                    return Json(tmp, JsonRequestBehavior.AllowGet);

                try
                {
                    products = tmp.AsQueryable();
                }
                catch (Exception)
                {
                    return Json("Azure không cho: products = tmp.AsQueryable()", JsonRequestBehavior.AllowGet);
                }
            }

            if(categoryId != null)
            {
                products = products.Where(p => p.CategoryId == categoryId);

                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }

            if (costBegin != null)
            {
                products = products.Where(p => p.Price >= costBegin);
                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }
            if (costEnd != null)
            {
                products = products.Where(p => p.Price <= costEnd);
                if (products.Count() == 0)
                    return Json(new List<Product>(), JsonRequestBehavior.AllowGet);
            }

            var result = new JsonNetResult
            {
                Data = products.ToList(),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                Settings = {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            MaxDepth = 3// product, productdetail, author
                }
            };
            return result;
        }
    }


}

BookStore/Views/Search/Index.cshtml
@model IEnumerable<BookStore.Models.Product>
@using System.Globalization;
@{
    ViewBag.Title = "Tìm kiếm sản phẩm | Nhà sách AC";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    CultureInfo ci = new CultureInfo("vi-VN");
}

@*<h2>Index</h2>


    @using (Html.BeginForm("Index", "Search", FormMethod.Get, new { @style = "margin:7px" }))
    {
        <input name="key" placeholder="Nhập từ khoá" type="text" />
        <input name="costBegin" placeholder="Giá bắt đầu" type="number" />
        <input name="costEnd" placeholder="Giá kết thúc" type="number" />
        <button type="submit">Tìm</button>
    }*@
<section>
    <div class="container">
        <div class="row">
            @Html.Partial("SideSearch")
            <div id="search_result" class="col-lg-9 padding-right">
                @foreach (var item in Model)
                {
                    <div class="col-lg-3">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center" style="height:230px">
                                    @if (string.IsNullOrEmpty(item.AvatarImage))
                                    {
                                        <img style="height:150px;width:100%;object-fit:contain"
                                             src="/Assets/images/home/default-image.png" />
                                    }
                                    else
                                    {
                                        <img style="height:150px;width:100%;object-fit:contain"
                                             src="@Url.Content(item.AvatarImage)"
                                             onerror="if (this.src != '/Assets/images/home/default-image.png') this.src = '/Assets/images/home/default-image.png';"/>
                                    }
                                    <h2>@(item.Price.ToString("0,0.###", ci)) đ</h2>
                                    <p class="shorten-name"><b>@item.Name</b></p>
                                </div>
                                <div class="product-overlay">
                                    <div class="overlay-content">
                                        <h2>@(item.Price.ToString("0,0.###", ci)) đ</h2>
                                        <p><a href="/Products/Single?id=@item.ID">@item.Name</a></p>
                                        <a href="#" class="btn btn-default add-to-cart" onclick="updateCart('add',@item.ID, event)">
                                            <p hidden>@item.ID</p>
                                            <i class="fa fa-shopping-cart"></i>
                                            Thêm vào giỏ
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<link href="~/Assets/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Assets/css/price-range.css" rel="stylesheet">
<script src="~/Assets/js/price-range.js" type="text/javascript"></script>
@*<script src="~/Assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>*@


<script>
    function onSearch() {
        var text = $('#search_box').val();
        var author = $('#ddl_author').val();
        var category = $('#ddl_category').val();
        var costBegin = $('#ex2').val().split(',')[0];
        var costEnd = $('#ex2').val().split(',')[1]; //$('#cost_end').val()
        $.ajax({// lấy dữ liệu từ link này
            url: '/Search/Search/',
            type: 'GET',
            dataType: 'json',// kiểu dữ liệu: json
            data: {
                "key": text,
                "authorId": author,
                "categoryId": category,
                "costBegin": costBegin,
                "costEnd": costEnd,
            },
            success: function (data) {// lấy dữ liệu thành công
                if (data == null) {
                    alert('Không tìm thấy');
                    return;
                }

                var items = '';
                $.each(data, function (i, item) {
                    items += genItem(item);
                });

                $('#search_result').html(items);
            },
            error: function (err) {// lỗi
                if (err.responseText)
                    alert(err.responseText);
                else {
                    $('#search_result').html('');
                    alert('Không tìm thấy kết quả');
                }
            }
        });

    }
    function genItem(item) {
        var content =
            '<div class="col-lg-3">\
                <div class="product-image-wrapper">\
                    <div class="single-products">\
                        <div class="productinfo text-center" style="height:230px">'

        if (!item.AvatarImage)
            content += '<img style="height:150px;width:100%;object-fit:contain" src="/Assets/images/home/default-image.png" alt="Không có hình" />'
        else
            content += '<img style="height:150px;width:100%;object-fit:contain" onerror="' + "if (this.src != '/Assets/images/home/default-image.png') this.src = '/Assets/images/home/default-image.png';" + '" src="' + item.AvatarImage.replace("~", "") + '" />'

        content +=
            '<h2>' + (item.Price).toLocaleString() + ' đ</h2>\
                            <p><b>' + item.Name + '</b></p>\
                        </div>'
            +
            '<div class="product-overlay">\
                            <div class="overlay-content">\
                                <h2>' + (item.Price).toLocaleString() + ' đ</h2>\
                                <p><a href="/Products/Single?id='+ item.ID + '">' + item.Name + '</a></p>\
                                <a href="#" class="btn btn-default add-to-cart" onclick="updateCart(' + "'add'," + item.ID + ', event)">\
                                    <i class="fa fa-shopping-cart"></i>\
                                    Thêm vào giỏ\
                                </a>\
                            </div>\
                        </div>\
                    </div>\
                </div>\
            </div>'
        return content;
    };

</script>

BookStore/Views/Search/SideSearch.cshtml
@{ 
    IEnumerable<BookStore.Models.Category> Categories =
        (ViewData["Categories"] as IList<BookStore.Models.Category>).OrderByDescending(cate=>cate.NumberOfProducts).Take(10);
    IEnumerable<BookStore.Models.Author> Authors =
        (ViewData["Authors"] as IList<BookStore.Models.Author>).OrderByDescending(a => a.NumberOfBooks).Take(10);
}

<div class="col-lg-3">
    <div class="left-sidebar">

        <!-- author -->
        <h2 style="margin-top:20px;margin-bottom:10px">Tác giả</h2>
        <select id="ddl_author" name="ddl_author"
                class="selectpicker" data-live-search="true"
                data-width="100%" data-size="5">
            <option value="">Toàn bộ</option>
            @foreach (var item in Authors)
            {
                <option value="@item.ID">@item.Name</option>
            }
        </select>
        <div class="brands-name" style="height:100%">
            <div id="list-author">
                <ul class="nav nav-pills nav-stacked">
                    @foreach (var item in Authors)
                    {
                        <li>
                            <a href="#">
                                <span class="pull-right">(@item.NumberOfBooks)</span>
                                <b>@item.Name</b>
                                <p hidden>@item.ID</p>
                            </a>
                        </li>
                    }
                </ul>

            </div>
        </div>

        <!-- category -->
        <h2 style="margin-top:20px;margin-bottom:10px">Danh mục</h2>
        <select id="ddl_category" name="ddl_category"
                class="selectpicker" data-live-search="true"
                data-width="100%" data-size="5">
            <option value="">Toàn bộ</option>
            @foreach (var item in Categories)
            {
                <option value="@item.ID">@item.Name</option>
            }
        </select>
        <div class="brands-name" style="height:100%">
            <div id="list-category">
                <ul class="nav nav-pills nav-stacked">
                    @foreach (var item in Categories)
                    {
                        <li>
                            <a href="#">
                                <span class="pull-right">(@item.NumberOfProducts)</span>
                                <b>@item.Name</b>
                                <p hidden>@item.ID</p>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="price-range">
            <h2 style="margin-top:20px;margin-bottom:5px">Tầm giá</h2>
            <div class="text-center">
                <input id="ex2" type="text" class="span2" value="" data-slider-min="0" data-slider-max="2000" data-slider-step="10" data-slider-value="[0,2000]" />
                <br /><b class="pull-left"> 0 VND</b> <b class="pull-right">2000 k</b>
            </div>
        </div><!--/price-range-->
    </div><!--/price-range-->
</div>


<link href="~/Assets/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Assets/css/bootstrap-select.min.css" rel="stylesheet">

@*<script src="~/Assets/js/jquery.js" type="text/javascript"></script>*@
<script src="~/Assets/js/price-range.js" type="text/javascript"></script>
<script src="~/Assets/js/bootstrap-select.min.js"></script>
<script src="~/Scripts/helper.js"></script>
<script>
    $("#ex2").slider({}).on("slideStop", function (e) {
        onSearch()
    });
    // lúc đầu show web
    $(document).ready(function () {
        @*//listAuthors();
        //listCategories();*@


        $("#ddl_author").change(function () {
            onSearch();
        });
        $("#ddl_category").change(function () {
            onSearch();
        });
        //bindSlider();
    })

    @*function listAuthors() {
        $.ajax({
            url: '/Products/DropdownAuthor',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                populateStdDropdown(data, "ddl_author");
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })
    }


    function listCategories() {
        $.ajax({
            url: '/Products/DropdownCategory',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                populateStdDropdown(data, "ddl_category");
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })
    }

    //function bindSlider() {
    //    var originalVal;
    //    $('.slider-track').on('slideStart', function (ev) {
    //        originalVal = $('#sl2').data('slider').getValue();
    //    });
    //    $('.slider-track').on('slideStop', function (ev) {
    //        var newVal = $('#sl2').data('slider').getValue();
    //        if (originalVal != newVal) {
    //            alert('Value Changed!');
    //        }
    //    });
    // get value of radios
    //alert($("input:radio[name='gender']:checked").val() + ' ' +
    //    $("input:radio[name='nogender']:checked").val());
    //}*@
    $("#list-category").on("click", "li>a", function (event) {
        event.preventDefault();

        var selected_cate = $(this).children('p').text();
        $('#ddl_category').val(selected_cate);
        $('#ddl_category').selectpicker('refresh');

        onSearch();
    });

    $("#list-author").on("click", "li>a", function (event) {
        event.preventDefault();

        var selected_author = $(this).children('p').text();
        $('#ddl_author').val(selected_author);
        $('#ddl_author').selectpicker('refresh');

        onSearch();
    });

</script>