BookStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using BookStore.Data;
using Newtonsoft.Json;

namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        BookStoreContext db = new BookStoreContext();

        // Thanh toán
        public ActionResult Index()
        {
            //CheckCustomerId();
            return View();
        }

        /// <summary>
        /// Get an order by id
        /// </summary>
        [HttpGet]
        public ActionResult GetCart(int? id, int? depth)
        {
            Order yourOrder;
            if (id != null)
            {
                yourOrder = db.Orders.Find(id);
                if (yourOrder == null)
                {
                    return null;
                }
            }
            else
            {
                yourOrder = CheckOrderId();
            }

            var result = new JsonNetResult
            {
                Data = yourOrder,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                Settings = {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                    MaxDepth = depth ?? 3// order, orderdetail, product
                }
            };

            return result;
        }

        #region Customer

        /// <summary>
        /// Get a customer by id
        /// </summary>
        [HttpGet]
        public ActionResult GetCustomer(int? id)
        {
            AnonymousUser customer;
            if (id != null)
            {
                customer = db.AnonymousUsers.Find(id);
                if (customer == null)
                {
                    return null;
                }
            }
            else
            {
                customer = CheckCustomerId();
            }

            var result = new JsonNetResult
            {
                Data = customer,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                Settings = {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            MaxDepth = 1// customer
                }
            };
            return result;
        }


        [HttpPost]
        public ActionResult UpdateCurrentCustomer(
            string firstName
            , string lastName
            , string telephone
            , string email
            , string address)
        {
            AnonymousUser customer = CheckCustomerId();

            customer.FirstName = firstName;
            customer.LastName = lastName;
            customer.PhoneNumber = telephone;
            customer.Email = email;
            customer.Address = address;


            db.Entry(customer).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return Json(
                new { success = true
                , text = "cập nhật thông tin khách hàng thành công" }
            , JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region cart update

        /// <summary>
        /// add product into the cart
        /// </summary>
        /// <param name="id">product Id</param>
        [HttpPost]
        public ActionResult AddProduct(int id)
        {
            ResultWeb result = new ResultWeb();
            Order cart = CheckOrderId();

            Product yourProduct = db.Products.Find(id);
            if(yourProduct == null)
            {
                //result.Type = ResultWeb.ResultType.NOT_FOUND;
                return Json(new
                {
                    success = false
                , text = "Không tìm thấy sản phẩm này"
                }, JsonRequestBehavior.AllowGet);
            }

            var details = cart.OrderDetails;

            if(details == null)
            {
                details = new List<OrderDetail>();
            }
            
            OrderDetail yourDetail = details.Where(od => od.ProductId == id).FirstOrDefault();
            // trường hợp đã thêm sản phẩm này rồi, thêm nó vào lần nữa
            if(yourDetail != null)
            {
                if(yourProduct.InStock <= yourDetail.Quantity)
                {
                    //result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
                    return Json(new
                    {
                        success = false
                ,
                        text = "Sản phẩm không đủ hàng"
                    }, JsonRequestBehavior.AllowGet);
                }
                
                yourDetail.Quantity += 1;
                yourDetail.TotalAmount = yourDetail.Quantity * yourProduct.Price;
                db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else// trường hợp chưa có sản phẩm này, thêm vào giỏ
            {
                if (yourProduct.InStock <= 0)
                {
                    //result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
                    return Json(new
                    {
                        success = false
                ,
                        text = "Sản phẩm không đủ hàng"
                    }, JsonRequestBehavior.AllowGet);
                }

                yourDetail = new OrderDetail
                {
                    OrderId = cart.ID,
                    ProductId = yourProduct.ID,
                    Quantity = 1,
                    TotalAmount = yourProduct.Price
                };
                db.OrderDetails.Add(yourDetail);
                db.SaveChanges();
                
            }

            RecalculateOrderCost(cart);

            //result.Type = ResultWeb.ResultType.OK;
            return Json(new
            {
                success = true
                ,
                text = "thêm sản phẩm vào giỏ thành công"
            }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// minus a product in the cart
        /// </summary>
        /// <param name="id">product id</param>
        [HttpPost]
        public ActionResult MinusProduct(int id)
        {
            ResultWeb result = new ResultWeb();
            Order cart = CheckOrderId();

            Product yourProduct = db.Products.Find(id);
            if (yourProduct == null)
            {
                //result.Type = ResultWeb.ResultType.NOT_FOUND;
                return Json(new
                {
                    success = false
                ,
                    text = "Không tìm thấy sản phẩm"
                }, JsonRequestBehavior.AllowGet);
            }

            var details = cart.OrderDetails;

            if(details == null)
            {
                return Json(new
                {
                    success = false
                ,
                    text = "Không tìm thấy chi tiết giỏ hàng"
                }, JsonRequestBehavior.AllowGet);
            }

            OrderDetail yourDetail = details.Where(od => od.ProductId == id).FirstOrDefault();
            if (yourDetail != null)
            {
                if(yourDetail.Quantity < 0)
                {
                    yourDetail.Quantity = 0;
                    yourDetail.TotalAmount = 0;
                    db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();

                    RecalculateOrderCost(cart);

                    //result.Type = ResultWeb.ResultType.FIELD_INVALID;
                    return Json(new
                    {
                        success = false
                ,
                        text = "Lỗi chi tiết giỏ hàng không xác định"
                    }, JsonRequestBehavior.AllowGet);
                }
                if(yourDetail.Quantity == 0)
                {
                    //result.Type = ResultWeb.ResultType.OK;
                    return Json(new
                    {
                        success = false
                ,
                        text = "Chi tiết giỏ hàng đã ở số nhỏ nhất"
                    }, JsonRequestBehavior.AllowGet);
                }

                string resultText = "";
                bool theSuccess = false;
                if (yourProduct.InStock < yourDetail.Quantity - 1)
                {
                    //result.Type = ResultWeb.ResultType.OUT_OF_STOCK;
                    theSuccess = false;
                    resultText = "Lỗi số lượng chi tiết giỏ hàng";
                    yourDetail.Quantity = yourProduct.InStock;
                }
                else
                {
                    //result.Type = ResultWeb.ResultType.OK;
                    theSuccess = true;
                    resultText = "Bớt sản phẩm thành công";
                    yourDetail.Quantity -= 1;
                }
                
                yourDetail.TotalAmount = yourDetail.Quantity * yourProduct.Price;
                db.Entry(yourDetail).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                RecalculateOrderCost(cart);

                return Json(new
                {
                    success = theSuccess
                ,
                    text = resultText
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //result.Type = ResultWeb.ResultType.FIELD_INVALID;
                return Json(new
                {
                    success = false
                ,
                    text = "Lỗi đơn hàng không hợp lệ"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// remove a product line in your cart
        /// </summary>
        /// <param name="id">the product id</param>
        [HttpPost]
        public ActionResult DeleteProduct(int id)
        {
            ResultWeb result = new ResultWeb();
            Order cart = CheckOrderId();

BookStore/Views/Shared/Admin_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Bootstrap Core CSS -->
    <link href="~/Assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Select CSS -->
    <link href="~/Assets/css/bootstrap-select.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Assets/css/sb-admin-2.min.css" rel="stylesheet">

    <link href="~/Assets/css/toast.css" rel="stylesheet">

    <!-- MetisMenu CSS
    <link href="~/Assets/css/metisMenu.min.css" rel="stylesheet"> -->
    <!-- Custom Fonts -->
    <link href="~/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    @RenderSection("AddToHead", false);
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Staff/">Bảng điều khiển</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="/Staff/UserProfile"><i class="fa fa-user fa-fw"></i> Trang cá nhân</a>
                </li>
                <li>
                    <a href="/Staff/LogOff"><i class="fa fa-sign-out fa-fw"></i> Đăng xuất</a>
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <div class="card" style="margin-left: auto;
                    margin-right: auto;
                    width: 8em">
                        @if(ViewBag.User.Avatar!= null)
                        {
                            <img class="card-img-top" src="@ViewBag.User.Avatar" alt="Card image cap"
                                 style="width:100%;height:100%;object-fit:contain"
                                 >
                        }
                        else
                        {
                            <img class="card-img-top" src="~/Assets/images/staff/avatar.png" alt="Card image cap">
                        }
                        <div class="card-body">
                            <p class="card-text">@(ViewBag.User.LastName +" "+ ViewBag.User.FirstName)</p>
                        </div>
                    </div>
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href=@Url.Action("Index", "Staff")><i class="fa fa-home fa-fw"></i> Dashboard</a>
                        </li>
                        @if (ViewBag.IsAdmin)
                        {
                        <li>
                            <a href=@Url.Action("ListProduct", "Staff")><i class="fa fa-tasks fa-fw"></i> Quản lý sản phẩm</a>
                        </li>
                        }
                        <li>
                            <a href=@Url.Action("ListOrder", "Staff")><i class="fa fa-file-text fa-fw"></i> Quản lý hóa đơn</a>
                        </li>
                        @if (ViewBag.IsAdmin)
                        {
                        <li>
                            <a onclick="alert('Chức năng này sẽ hoàn thiện sớm.')"><i class="fa fa-shopping-cart fa-fw"></i> Quản lý giao dịch</a>
                        </li>
                        <li>
                            <a href=@Url.Action("ListAuthor", "Staff")><i class="fa fa-fw"></i> Quản lý tác giả</a>
                        </li>
                        <li>
                            <a href=@Url.Action("ListPublisher", "Staff")><i class="fa fa-briefcase fa-fw"></i> Quản lý nhà xuất bản</a>
                        </li>
                        }
                        @*<li>
                            <a href="forms.html"><i class="fa fa-book fa-fw"></i> Quản lý blog</a>
                        </li>
                        <li>
                            <a href="forms.html"><i class="fa fa-users fa-fw"></i> Quản lý thành viên</a>
                        </li>*@
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Assets/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Assets/js/bootstrap.min.js"></script>

    <!-- Bootstrap Select JavaScript -->
    <script src="~/Assets/js/bootstrap-select.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Assets/js/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Assets/js/sb-admin-2.js"></script>

</body>

</html>

BookStore/Views/Shared/Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="subscribe">
                        <div>
                            <h2>THEO DÕI SHOP</h2>
                            <p>Chúng tôi sẽ gửi thông tin về các sản phẩm và khuyến mãi mới qua email</p>
                        </div>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Nhập email bạn hay dùng" />
                            <button type="submit" class="subscribe-button">Đăng ký</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                    <div class="single-widget">
                        <h2>HỖ TRỢ KHÁCH HÀNG</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Các câu hỏi thường gặp</a></li>
                            <li><a href="#">Gửi yêu cầu hỗ trợ</a></li>
                            <li><a href="#">Hướng dẫn đặt hàng</a></li>
                            <li><a href="#">Phương thức vận chuyển</a></li>
                            <li><a href="#">Chính sách đổi trả</a></li>
                            <li><a href="#">Hướng dẫn mua trả góp</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="single-widget">
                        <h2>HỒ CHÍ MINH</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Chi nhánh Quận 1</a></li>
                            <li><a href="#">Chi nhánh Quận 5</a></li>
                            <li><a href="#">Chi nhánh Bình Thạnh</a></li>
                            <li><a href="#">Chi nhánh Thủ Đức</a></li>
                            <li><a href="#">Chi nhánh Quận 3</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="single-widget">
                        <h2>KHÁC</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Điều khoản sử dụng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Chính sách hoàn tiền</a></li>
                            <li><a href="#">Thanh toán</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="single-widget">
                        <h2>VỀ CHÚNG TÔI</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="/Contact/">Thông tin công ty</a></li>
                            <li><a href="/Contact/">Liên kết</a></li>
                            <li><a href="/Contact/">Bản quyền</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer><!--/Footer-->

BookStore/Views/Shared/Header.cshtml
<style>
    .dropbtn {
        border: none;
        cursor: pointer;
    }

    .dropdown-cart {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: rgba(191, 252, 254, 0.78);
        padding: 0px;
        margin: 0px;
        width: 450px;
        height: auto;
        right: 0;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1;
    }

    .dropdown-cart:hover .dropdown-content {
        display: block;
    }
</style>
<header id="header">
    <!--header-->
    <div class="header-bottom sticky-navbar">
        <!--header-bottom-->
        <div class="container logo-container">
            <div class="row">
                <div class="col-lg-2">
                    <a href=@Url.Action("Index", "Home")><img src="~/Assets/images/home/logo.png" style="width:100px;height:50px"/></a>
                </div>
                <div class="col-lg-7">
                    <div class="search_box">
                        <input id="search_box" type="search" placeholder="Tìm kiếm"
                               onkeypress="onKeypressSearch(event)" />
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li class="dropdown-cart">
                                <a class="dropbtn shopping-cart" href=@Url.Action("Index", "Cart")>
                                    <img src="~/Assets/images/home/shopping-cart.png" style="width:32px;height:32px" />
                                </a>
                                <div class="dropdown-content">
                                    <table class="table table-fixed-preview">
                                        <thead>
                                            <tr class="cart_menu">
                                                <th class="description col-xs-5">Sản phẩm</th>
                                                <th class="price col-xs-1" style="text-align:center">Giá</th>
                                                <th class="quantity col-xs-3" style="margin-left:10px">Số lượng</th>
                                                <th class="total col-xs-2">Tổng</th>
                                            </tr>
                                        </thead>
                                        <tbody class="cart-body-prv"></tbody>
                                    </table>
                                </div>
                            </li>
                            <li><a href=@Url.Action("Login", "Staff")><i class="fa fa-lock"></i> Đăng nhập</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="container menu-container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                            <li>@Html.ActionLink("Liên hệ", "Index", "Contact")</li>
                            <li>@Html.ActionLink("Các sản phẩm", "Index", "Search")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

<script src="~/Assets/js/jquery.js" type="text/javascript"></script>


<script>
    $(document).ready(function () {
        getCart("preview");
    })
    
    function getCart(viewType) {
        $.ajax({
            url: '/Cart/GetCart',
            type: 'GET',
            dataType: 'json',
            data: { "id": null },
            success: function (data) {
                populateOrderDetails(data.OrderDetails, viewType);
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })
    }

    function populateOrderDetails(data, viewType) {
        var rows = '';
        var iurl;
        if (viewType == "preview") {
            $.each(data, function (i, item) {
                
                if (item.Product.AvatarImage) {
                    iurl = item.Product.AvatarImage.replace("~", "");
                }
                else {
                    iurl = "/Assets/images/home/default-image.png"
                }
                if (item.Quantity == 0) {
                    return true;
                }
                rows += '<tr style="height:57px">'
                rows += '                                 <td class="cart_description col-xs-5"> <img style="vertical-align:middle;float:left;max-height:50px;max-width:50px;object-fit:contain;margin-right:4px" onerror="' + "if (this.src != '/Assets/images/home/default-image.png') this.src = '/Assets/images/home/default-image.png';" + '" src="' + iurl + '" width="40px" height="40px"></a>'
                rows += '                                     <h4 style="margin:0"><a href="/Products/Single?id=' + item.Product.ID + '" class="shorten-name" style="background-color:transparent;color:#0fb3bc; font-weight:bold;white-space: pre-wrap;margin:0">' + item.Product.Name + '</a></h4>'
                rows += '                                   </td>'
                rows += '                                   <td class="cart_price col-xs-1" style="line-height:57px;padding:0">'
                rows += '                                       <p style="margin:0;text-align:center" >' + (item.Product.Price / 1000).toLocaleString() + 'k</p>'
                rows += '                                   </td>'
                rows += '                                  <td class="cart_quantity col-xs-3" style="margin-right:-10px">'
                rows += '                                     <div class="cart_quantity_button"> <p hidden>' + item.ProductId + '</p>'
                rows += '                                        <a style="height:20px" class="cart_quantity_up" href="">+</a>'
                rows += '                                       <input style="height:28px" class="cart_quantity_input_prv" type="text" name="quantity" readonly value="' + item.Quantity + '" autocomplete="off" size="2">'
                rows += '                                      <a style="height:20px" class="cart_quantity_down" href="">-</a>'
                rows += '                                 </div>'
                rows += '                            </td>'
                rows += '                           <td class="cart_total col-xs-2" style="line-height:57px;padding:0">'
                rows += '                              <p style="margin:0;text-align:center" class="cart_total_price">' + (item.TotalAmount / 1000).toLocaleString() + 'k</p>'
                rows += '                         </td>'
                rows += '                        <td class="cart_delete" style="padding-right:0"><p hidden>' + item.ProductId + '</p>'
                rows += '                           <a class="cart_quantity_delete" style="background-color:transparent" href=""><i class="fa fa-times"></i></a>'
                rows += '                      </td>'
                rows += '                 </tr>';
            });
            $(".cart-body-prv").html(rows);
        }
        else if (viewType == "main") {
            $.each(data, function (i, item) {
                if (item.Product.AvatarImage) {
                    iurl = item.Product.AvatarImage.replace("~", "");
                }
                else {
                    iurl = "/Assets/images/home/default-image.png"
                }
                if (item.Quantity == 0) {
                    return true;
                }
                rows += '<tr>'
                rows += '              <td class="cart_description col-lg-5"> <a href="/Products/Single?id=' + item.Product.ID + '"><img style="float:left" onerror="' + "if (this.src != '/Assets/images/home/default-image.png') this.src = '/Assets/images/home/default-image.png';" + '" src="' + iurl + '" width="60px" height="60px"></a>'
                rows += '                  <h4><a style="margin-left:5px" href="/Products/Single?id=' + item.Product.ID + '">' + item.Product.Name + '</a></h4>'
                rows += '             <p><text style="margin-left:5px">Mã hàng: ' + item.Product.ID + '</text></p>'
                rows += '         </td>'
                rows += '         <td class="cart_price col-lg-2" style="text-align:center">'
                rows += '             <p style="margin:0">' + (item.Product.Price / 1000).toLocaleString() + 'k</p>'
                rows += '         </td>'
                rows += '         <td class="cart_quantity col-lg-2">'
                rows += '             <div class="cart_quantity_button"> <p hidden>' + item.ProductId + '</p>'
                rows += '                 <a style="height:23px" class="cart_quantity_up" href="">+</a>'
                rows += '                 <input style="height:23px" class="cart_quantity_input" type="text" name="quantity" readonly value="' + item.Quantity + '" autocomplete="off" size="2">'
                rows += '                 <a style="height:23px" class="cart_quantity_down" href="">-</a>'
                rows += '             </div>'
                rows += '         </td>'
                rows += '         <td class="cart_total col-lg-2" style="text-align:center">'
                rows += '             <p style="margin:0" class="cart_total_price">' + (item.TotalAmount / 1000).toLocaleString() + 'k</p>'
                rows += '         </td>'
                rows += '         <td class="cart_delete"> <p hidden>' + item.ProductId + '</p>'
                rows += '             <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>'
                rows += '         </td>'
                rows += '     </tr>'
            });
            $(".cart-body").html(rows);
        }

    }
    $(".cart-body-prv").on("click", "tr>td>div>.cart_quantity_up", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("add", productID, event)
    });

    $(".cart-body-prv").on("click", "tr>td>div>.cart_quantity_down", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("minus", productID, event)
    });

    $(".cart-body-prv").on("click", "tr>td>.cart_quantity_delete", function (event) {
        event.preventDefault();
        var productID = $(this).parent().children('p').text();
        updateCart("delete", productID, event)
    });


    function updateCart(action, productID, event) {
        event.preventDefault();
        var actionurl = ''

        switch (action) {
            case "add":
                actionurl = '/Cart/AddProduct'
                break;
            case "minus":
                actionurl = '/Cart/MinusProduct'
                break;
            case "delete":
                actionurl = '/Cart/DeleteProduct'
                break;
        }

        $.ajax({
            url: actionurl,
            type: 'POST',
            dataType: 'json',
            data: { "id": productID },
            success: function (data) {

                if (!data.success) {
                    alert(data.text);
                }

                getCart("preview");
                getCart("main");
            },
            error: function (err) {
                alert(err.responseJSON);
                document.write(err.responseText);
            }
        })

    }


    @*$("#search_box").click(function () {

        var currentpage = '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()'
        if (currentpage != 'Search') {
            window.location.href = '@Url.Action("Index","Search")'
        }

    });*@
    function onKeypressSearch(e) {
        var keynum;

        if (window.event) { // IE                    
            keynum = e.keyCode;
        } else if (e.which) { // Netscape/Firefox/Opera                   
            keynum = e.which;
        }

        if (keynum == 13) {
            onSearch();
        }
    }

</script>